import type { Metadata } from "next";
import { Birthstone, Geist, Geist_Mono, Limelight } from "next/font/google";

import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const limelight = Limelight({
    variable: "--font-limelight",
    subsets: ["latin"],
    weight: "400",
});

const birthstone = Birthstone({
    variable: "--font-birthstone",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${limelight.variable} ${birthstone.variable} antialiased`}
            >
                <main>{children}</main>
                <Toaster richColors />
            </body>
        </html>
    );
}
